version: '3.5'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  adapter:
    image: clojure
    command: lein run
    working_dir: /srv
    volumes:
      - ".:/srv"
    environment:
      JAEGER_SERVICE_NAME: "batch-processor"
      JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    depends_on:
      - jaeger
